version: "3.1"

services:
    database:
        image: mongo

        restart: always

    application:
        build: "./"
        command: npm run start
        restart: always
        ports:
            - "3000:3000"
        environment:
            - MONGO_URI=mongodb://database:27017/todo
            - LOGGER_LEVEL=${LOGGER_LEVEL}
            - SECRET=${SECRET}
            - NODE_ENV=${NODE_ENV}
            - SERVER_PORT=3000
        depends_on:
            - database
